### ISSUE TITLE
The unsafe article states a runtime.KeepAlive call is needed in the String2ByteSlice example. This is wrong.

### ISSUE THREAD

**Issue by go101** [go101/go101#151]
@bcmills's opinion is right in [this thread](https://github.com/golang/go/issues/25484).

```
func String2ByteSlice(str string) (bs []byte) {
	strHdr := (*reflect.StringHeader)(unsafe.Pointer(&str))
	sliceHdr := (*reflect.SliceHeader)(unsafe.Pointer(&bs))
	sliceHdr.Data = strHdr.Data
	sliceHdr.Cap = strHdr.Len
	sliceHdr.Len = strHdr.Len
	// This KeepAlive line is essential to make the
	// String2ByteSlice function be always valid
	// when it is used in other custom packages.
	runtime.KeepAlive(&str)
	return
}
```

Bryan C. Mills said `The GC tracks pointers through their original allocations — the pointer scan does not care about lexical types, only allocation types.`

@tliron, as that old thread is frozen, so I created this thread to let you get acknowledged.

**Comment by tliron** [comment]
@go101 I'm confused, the commit specifically removes the KeepAlive as non-essential, but there you are showing its use. Could be you please clarify whether it's required or not?

**Comment by go101** [comment]
@tliron  What is shown here is the old code. The new one in the book has commented out the KeepAlive call.

**Comment by go101** [comment]
@bcmills
I get confused again on this now. ;(

```Go
func String2ByteSlice(str string) (bs []byte) {

	// Without the KeepAlive call, is it possible that compilers think
	// the underlying bytes of str is collectable now? From the safe
	// pointer using view, it looks the bytes of the string is not used
	// any more here.

	strHdr := (*reflect.StringHeader)(unsafe.Pointer(&str))

	// The reason "the pointer scan does not care about lexical types, only allocation types"
	// is valid only if the bytes of the string hasn't been collected yet here.

	sliceHdr := (*reflect.SliceHeader)(unsafe.Pointer(&bs))
	sliceHdr.Data = strHdr.Data
	sliceHdr.Cap = strHdr.Len
	sliceHdr.Len = strHdr.Len

	// runtime.KeepAlive(&str)
	return
}
```

**Comment by cuonglm** [comment]
@go101 

> 	// Without the KeepAlive call, is it possible that compilers think
	// the underlying bytes of str is collectable now? From the safe
	// pointer using view, it looks the bytes of the string is not used
	// any more here.

No, the compiler won't _think_ the underlying bytes of str is collectable. Instead, because `str` is address taken, the compiler emitted a stack object for tracking its liveness.

See `runtime/mgcstack.go` for details implementation and https://docs.google.com/document/d/1un-Jn47yByHL7I0aVIP_uVCMxjdM5mpelJhiKlIqxkE/edit for design doc.

**Comment by go101** [comment]
I understand these. In fact, this is how `runtime.KeepAlive` function is implemented (by using a pointer to the value which needed to keep alive).

But what is the meaningfulness of the `runtime.KeepAlive` function? Is it always okay to make sure a value will not be collected by using a custom KeepAlive function?

**Comment by bcmills** [comment]
> But what is the meaningfulness of the `runtime.KeepAlive` function?

The main use of `runtime.KeepAlive` is to facilitate the abuse of `runtime.SetFinalizer` to manage resources outside of the Go heap (such as file descriptors, C objects, or mmap'd memory regions).

Without `runtime.KeepAlive`, in some cases a Go object can become unreachable while the external resources to which it refers are still in use (because those references occur in temporary variables).

**Comment by go101** [comment]
Okay, I got it. Thanks both the explanations.
