### ISSUE TITLE
channel-closing: context is not mentioned

### ISSUE THREAD

**Issue by vitaly-zdanevich** [go101/go101#194]
https://github.com/go101/go101/blob/2e1ab98ae02a96310bb901ed7ade2205d87ed26c/articles/channel-closing.html#L1

This is difficult code with so many channels. I think that Context package should be mentioned, because
* Semantic: Context is more about cancellation signal, when somebody will read the code
* A Context is safe for simultaneous use by multiple goroutines: a CancelFunc may be called by multiple goroutines simultaneously - so we do not need to invent some protection about multiple channel close

**Comment by go101** [comment]
@vitaly-zdanevich 
Go 101 is mainly focus on basic syntax/semantic and runtime things.
The `context` package is a general package, so Go 101 doesn't touch it in detail.
It is only mentioned a bit in this article: https://go101.org/article/channel-use-cases.html

This issue is some duplicated with https://github.com/go101/go101/issues/163

**Comment by go101** [comment]
@vitaly-zdanevich

I will close this issue soon. Further discussions are still welcome here.
