### ISSUE TITLE
Typo in Go Optimizations 101

### ISSUE THREAD

**Issue by wdscxsj** [go101/go101#236]
2nd to last line on p. 59 of the PDF (2022-5-6 version), "escaped time" should be "elapsed time".

**Comment by wdscxsj** [comment]
Just see there is an updated version on 2022-8-29, and the typo is on p. 60.

A summary of the updates in the book would be nice.

**Comment by go101** [comment]
@wdscxsj
Thanks for this finding. It will be fixed in the next release.

I will write a Go 101 blog to list the changes in recent Go 101 book releases.

Here is a summary for the last release of Go Optimizations 101:
* the `Garbage Collection` chapter is updated much. The update contents are mainly in the last 4 sections (starting the `Use new heap memory percentage strategy to control automatic GC frequency` section). Some descriptions in the first section `GC pacer` are also modified a bit.
* in the `Stack and Escape Analysis` chapter, the descriptions about initial stack sizes in the `Stacks growth and shrinkage` section are modified.
* in the `BCE` chapter, a new `Example 4` section is added. The example was in the `Sometimes, the compiler needs some hints to remove some bound checks` section.
* in the `Functions` chapter, the `Which functions are inline-able?` section states that functions containing `select` code blocks may be inlined since Go toolchain 1.19.

**Comment by wdscxsj** [comment]
Thank you very much! I'll go over the updated parts.
